build: Fix a build error due to missing errno.h
This patch is to fix the following build error for ARM arch.

  libmcount/plthook.c:899:20: error: 'errno' undeclared

Signed-off-by: Honggyu Kim <honggyu.kp@gmail.com>