test: Skip if build failed
When g++ is missing, it should skip the test with 'build fail' mark.
But it currently stops the whole build with following:

  Traceback (most recent call last):
    File "./runtest.py", line 291, in <module>
      result = run_single_case(name, flags, opts.split(), arg.diff)
    File "./runtest.py", line 222, in run_single_case
      ret = tc.build(cflags)
    File "/uftrace/tests/runtest.py", line 53, in build
      return sp.call(build_cmd.split(), stdout=sp.PIPE, stderr=sp.PIPE)
    File "/usr/lib64/python2.7/subprocess.py", line 523, in call
      return Popen(*popenargs, **kwargs).wait()
    File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
      errread, errwrite)
    File "/usr/lib64/python2.7/subprocess.py", line 1343, in _execute_child
      raise child_exception
  OSError: [Errno 2] No such file or directory
  Makefile:13: recipe for target 'test_run' failed
  make[1]: *** [test_run] Error 1
  Makefile:225: recipe for target 'test' failed
  make: *** [test] Error 2

Signed-off-by: Namhyung Kim <namhyung@gmail.com>