uftrace: Show an error message if open failed
Instead of exiting silently.

  $ uftrace replay -d xyz
  uftrace: /home/namhyung/project/uftrace/cmd-replay.c:913:command_replay
   ERROR: cannot open data: xyz: No such file or directory

Signed-off-by: Namhyung Kim <namhyung@gmail.com>