test: Handle empty output due to optimization
On my debian ARM, forkexec tests are optimized out so test failed with
following:

  # ftrace t-forkexec
  # DURATION    TID     FUNCTION
   271.668 us [ 5837] | __cxa_atexit();

  ftrace stopped tracing with remaining functions
  ===============================================
  task: 5837
  [0] main

  # ./runtest.py forkexec
  Test case             -finstrument-f -pg
  --------------------: O0 O1 O2 O3 Os O0 O1 O2 O3 Os
  Traceback (most recent call last):
    File "./runtest.py", line 231, in <module>
      result = run_single_case(name)
    File "./runtest.py", line 182, in run_single_case
      ret = tc.run()
    File "/root/ftrace/tests/runtest.py", line 109, in run
      result_tested = self.sort(p.communicate()[0].decode())  # for python3
    File "/root/ftrace/tests/t010_forkexec.py", line 65, in sort
      return TestBase.sort(self, output, True)
    File "/root/ftrace/tests/runtest.py", line 87, in sort
      result += '\n'.join(pids[pid_list[0]]['result'])
    IndexError: list index out of range
    make: *** [test] Error 1

Signed-off-by: Namhyung Kim <namhyung@gmail.com>