mcount: Fix a compiler error in mcount-arch.h
It doesn't know about struct symtabs.  Add forward declaration to fix it.

    CC FPIC  arch/arm/mcount-support.op
  In file included from /home/namhyung/uftrace/arch/arm/mcount-support.c:10:0:
  /home/namhyung/uftrace/arch/arm/mcount-arch.h:63:10:
    warning: ‘struct symtabs’ declared inside parameter list [enabled by default]
  /home/namhyung/uftrace/arch/arm/mcount-arch.h:63:10:
    warning: its scope is only this definition or declaration, which is
             probably not what you want [enabled by default]
  /home/namhyung/uftrace/arch/arm/mcount-support.c:250:16:
    error: conflicting types for ‘mcount_arch_parent_location’
  /home/namhyung/uftrace/arch/arm/mcount-arch.h:61:17:
    note: previous declaration of ‘mcount_arch_parent_location’ was here
  make[1]: *** [/home/namhyung/uftrace/arch/arm/mcount-support.op] Error 1

Signed-off-by: Namhyung Kim <namhyung@gmail.com>