dump: Fix error on graphviz with C++ symbols
The DOT language may treat the 'dot' ('.') character specially and
symbols having it caused a syntax error.  This happens with some C++
programs (or probably with C programs + compiler optimization).

  $ dot -Tpng clang.dot -o clang.png
  Error: clang.dot: syntax error in line 12 near '.'

The 12th line was:

  _GLOBAL__sub_I_cc1_main.cpp[xlable = "Calls : 1"]

Making it string literal fixes the issue.

Signed-off-by: Honggyu Kim <honggyu.kp@gmail.com>
Signed-off-by: Namhyung Kim <namhyung@gmail.com>