build: Add missing 'riscv64' to configure --arch
The configure script didn't accept the riscv target arch and failed like
below when I tried to cross-build:

  $ ./configure --arch=riscv64 --cross-compile=riscv64-linux-gnu-
  Error: 'riscv64' is not a supported architecture

Also change the script to use 'case' statement to handle multiple
architectures easily.

Signed-off-by: Namhyung Kim <namhyung@gmail.com>