build: Check dependency of libelf
The libelf library is required to build uftrace.  Add it to the
dependency list and show error message on configure if missing.

  $ ./configure
  Error: Cannot find 'libelf': Please install it first.

Signed-off-by: Namhyung Kim <namhyung@gmail.com>