record: create fallback channel when mkfifo() fails
Specifically, some file systems like vboxsf and FAT do not support
mkfifo(). As a result, the 'uftrace record' fails when creating the
.channel file for communication.

    # uftrace record -vvv -P . ./spintest
    uftrace: running uftrace v0.14-21-gafed ( x86_64 dwarf python3 luajit tui perf sched dynamic  )
    uftrace: checking binary ./spintest
    uftrace: removing uftrace.data.old directory
    uftrace: /home/vagrant/uftrace/cmds/record.c:2273:command_record
     ERROR: cannot create a communication channel: Operation not permitted

This patch, creates a fallback channel through 'tmpfs', which does
support mkfifo(). In this suggestion, the .channel file will be named
as the following. '/tmp/<dirname>.channel'

Signed-off-by: Daniel T. Lee <danieltimlee@gmail.com>