build: Fix build errors on !HAVE_LIBCAPSTONE
The mcount_disasm_{init,finish} are defined only when capstone support
is enabled.  So it'd fail to build due to undefined symbols if it's not
supported like below:

  $ ./configure --without-capstone

  $ make
  ...
    LINK     libmcount/libmcount.so
  /usr/bin/ld: /home/namhyung/project/uftrace/arch/x86_64/mcount-arch.a(mcount-support.op):
    (.data.rel.ro+0x78): undefined reference to `mcount_disasm_init'
  collect2: error: ld returned 1 exit status
  make: *** [Makefile:292: /home/namhyung/project/uftrace/libmcount/libmcount.so] Error 1
  make: *** Waiting for unfinished jobs....

Reported-by: Jun Yeong Kim <junyeonggim5@gmail.com>
Signed-off-by: Namhyung Kim <namhyung@gmail.com>