test: Fix compile errors without libdw
Some unit test code in utils/dwarf.c uses functions defined under
HAVE_LIBDW so the test code should be the same.

    CC       utils/dwarf.ot
  utils/dwarf.c: In function ‘func_dwarf_srcline_prefix1’:
  utils/dwarf.c:2255:17: warning: implicit declaration of function ‘add_comp_dir’ [-Wimplicit-function-declaration]
   2255 |                 add_comp_dir(&dirs, test_dirs[i].name, test_dirs[i].nr_loc);
        |                 ^~~~~~~~~~~~
  In file included from <command-line>:
  utils/dwarf.c:2259:20: warning: implicit declaration of function ‘get_base_comp_dir’ [-Wimplicit-function-declaration]
   2259 |         TEST_STREQ(get_base_comp_dir(&dirs), "/home/soft/uftrace/cmds");
        |                    ^~~~~~~~~~~~~~~~~

Signed-off-by: Namhyung Kim <namhyung@gmail.com>