test: Fix clang X-ray test failure
There was some build failure for the X-ray test case:

  build command: clang -o t-abc -fno-inline -fno-builtin \
                 -fno-omit-frame-pointer  -fxray-instrument \
		 -fxray-instruction-threshold=1  s-abc.c
     /usr/lib/clang/5.0.1/lib/linux/libclang_rt.xray-x86_64.a
     (xray_inmemory_log.cc.o): In function `__xray_OpenLogFile()':
     (.text._ZL18__xray_OpenLogFilev+0x81): undefined reference to
     `__cxa_guard_acquire'
     (.text._ZL18__xray_OpenLogFilev+0x9e): undefined reference to
     `__cxa_guard_release'
     ...

It was due to missing C++ dependency, fix it by adding '-lstdc++'.

Signed-off-by: Namhyung Kim <namhyung@gmail.com>