test: Do not use sys/auxv.h in unittest
It was added in glibc-2.16 so older systems cannot run the test code

  $ make test
  unittest.c:7:22: fatal error: sys/auxv.h: No such file or directory
  compilation terminated.
  make[1]: /otc/ftrace/blob/master/**** [unittest] Error 1
  make: *** [test] Error 2

Reported-by: Honggyu Kim <hong.gyu.kim@lge.com>
Signed-off-by: Namhyung Kim <namhyung@gmail.com>