tests: Fix t052_nested_func.py test in clang
Since clang doesn't allow nested function, t052_nested_func test is not
meaningful and it fails to compile the source code as follows.

  $ clang tests/s-nested.c
  s-nested.c:7:51: error: function definition is not allowed here
          __attribute__((noinline)) int foo_internal(void) {
                                                           ^
  s-nested.c:11:9: warning: implicit declaration of function 'foo_internal' is invalid in C99 [-Wimplicit-function-declaration]
          return foo_internal();
                 ^
  s-nested.c:18:69: error: function definition is not allowed here
          __attribute__((noinline)) int compar(const void *a, const void *b) {
                                                                             ^
  s-nested.c:25:57: error: use of undeclared identifier 'compar'
          qsort(arr, sizeof(arr)/sizeof(arr[0]), sizeof(arr[0]), compar);
                                                                 ^
  1 warning and 3 errors generated.

So this patch disables the test only for clang.

Signed-off-by: Honggyu Kim <honggyu.kp@gmail.com>