record: Add shmem directory to exec permission
The shmem directory under TMPDIR is used to store named pipe for
communication.  Since the named pipe is created under the created
'uftrace' directory, the 'uftrace' directory has to have an exec
permission so that named pipe files can be created inside it.

This patch fixes the problem by adding exec permission for 'uftrace'
directory creation.

Before:
  $ uftrace record --force pwd
  mcount: /data/data/com.termux/files/home/uftrace/libmcount/record.c:81:prepare_shmem_buffer
   ERROR: mmap shmem buffer: Permission denied

After:
  $ uftrace record --force pwd
  /data/data/com.termux/files/home/uftrace

Signed-off-by: Honggyu Kim <honggyu.kp@gmail.com>