test: Fix kernel version parsing
I found the kernel tests are failing on Fedora due to the version
string.  On my machine it looks like:

  $ uname -r
  6.14.11-200.fc41.x86_64

But the current code expect 3 numbers splitted by '.' and it caused the
following error regardless of actual test result.

  Traceback (most recent call last):
    File "/home/namhyung/project/uftrace/tests/./runtest.py", line 1111, in <module>
      results = run_single_case(name, flags, opts.split(), arg, compilers)
    File "/home/namhyung/project/uftrace/tests/./runtest.py", line 815, in run_single_case
      ret, dif = tc.run(case, cflags, arg.diff, timeout)
                 ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/namhyung/project/uftrace/tests/runtest.py", line 672, in run
      result_expect = self.sort(self.fixup(cflags, self.result))
                                ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
    File "/home/namhyung/project/uftrace/tests/t079_replay_kernel_D.py", line 48, in fixup
      major, minor, release = uname[2].split('.')
      ^^^^^^^^^^^^^^^^^^^^^
  ValueError: too many values to unpack (expected 3)
  make[1]: *** [Makefile:41: test_all] Error 1
  make: *** [Makefile:420: test] Error 2

Fix it by adding 'maxsplit' argument to Python's split() function which
will return maxsplit+1 arguments.

Signed-off-by: Namhyung Kim <namhyung@gmail.com>