build: Fix a build error on i386
It happened to have common.S as well as common.c, so it picked the .S
before .c for the uftrace-arch.a.  And it caused undefined symbols.

  /usr/bin/ld: libmcount/symbol.op: in function `load_dynsymtab':
  utils/symbol.c:722:(.text+0x2b19): undefined reference to `uftrace_arch_ops'
  libmcount/symbol.op: in function `load_elf_dynsymtab':
  utils/symbol.c:586:(.text+0x184a): undefined reference to `uftrace_arch_ops'

Fixed: #2010
Signed-off-by: Namhyung Kim <namhyung@gmail.com>