build: Fix build failure of unittest binary
When $(srcdir) != $(objdir) following error will occur.

  $ mkdir build && cd build
  $ ../configure
  $ make test
  ...
    CC       uftrace.ot
    CC       cmds/dump.ot
  cmds/dump.c:9:21: fatal error: uftrace.h: No such file or directory

This was because of recent change afbbf65c ("test: Build unittest
objects when config changed") which changed the build directory.

Signed-off-by: Namhyung Kim <namhyung@gmail.com>