record: Add message for missing argument/retval
When a binary is built with -finstrument-functions, it cannot support
argument and/or return value.  Warn the user about it and make --force
ignores this case.

  $ ftrace -A '.*@arg1' abc-cyg
  ftrace: /home/namhyung/project/ftrace/cmd-record.c:1146:check_binary
   ERROR: -A and/or -R option can be used only for binaries
          built with -pg flag.  Use --force option if you want to proceed
          with no argument and/or return value info.

Signed-off-by: Namhyung Kim <namhyung@gmail.com>