record: check both libpath value and +"/libmcount" for -L option
When the -L option is used, the below error can occur:

  $ uftrace -L /home/taeung/lib/ t-abc
  ERROR: ld.so: object '/home/taeung/lib/libmcount/libmcount-fast.so' from LD_PRELOAD cannot be preloaded ...

Because currently libpath + "/libmcount"(for test) is only used
instead of original libpath the user gave with -L
So check both for -L option.

Signed-off-by: Taeung Song <treeze.taeung@gmail.com>