script/python: Ignore errors when decoding strings
It's possible to have some broken argument/return values.  For example
my data has following and it caused script command failed

  $ uftrace replay -F atoi
  # DURATION     TID     FUNCTION
     0.563 us [626346] | atoi("-1
  <81><DA>U") = -1;
              [626349] | } = 0; /* fork */

  $ uftrace script -S count.py
  Traceback (most recent call last):
    File "/home/namhyung/project/uftrace/scripts/count.py", line 14, in uftrace_end
      print(count)
  SystemError: PyEval_EvalFrameEx returned a result with an error set

With -v option, it showed:

  UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 3: invalid start byte

So ignore any error during string decode for now.

Signed-off-by: Namhyung Kim <namhyung@gmail.com>