symbol: Fix a symbol-finding bug on ARM
In some 32-bit systems (e.g., ARM), the kernel start address may changed by
`VMSPLIT_*G` configuration. However uftrace assumed the kernel start address
at 0x8000_0000 on 32-bit systems. Due to the assumption, `is_real_address()`
returns nonexistent or wrong address in case of VMSPLIT_1G or VMSPLIT_3G.
Finally, it causes symbol not found error as below.

root@kesl:~/uftrace/tests# ./runtest.py 076
Test case pg finstrument-fu
--------------------: O0 O1 O2 O3 Os O0 O1 O2 O3 Os
uftrace: /root/uftrace/arch/arm/mcount-support.c:263:mcount_arch_parent_location
ERROR: cannot find symbol for b6efd631
uftrace: /root/uftrace/arch/arm/mcount-support.c:263:mcount_arch_parent_location
ERROR: cannot find symbol for b6f2b65f
uftrace: /root/uftrace/arch/arm/mcount-support.c:263:mcount_arch_parent_location
ERROR: cannot find symbol for b6f1565f
uftrace: /root/uftrace/arch/arm/mcount-support.c:263:mcount_arch_parent_location
ERROR: cannot find symbol for b6f4665f
uftrace: /root/uftrace/arch/arm/mcount-support.c:263:mcount_arch_parent_location
ERROR: cannot find symbol for b6f7a65d
076 lib_replay_F : NG NG NG NG NG NG NG NG NG NG

This patch contained that `is_real_address()` returns correct address along the
`VMSPLIT_*G` configuration. It also contained that `uftrace record` and
`uftrace replay` can be run on different machines.

NOTE: This patch works on arm32 and x86_64 only.

Signed-off-by: Wonseok Ko <wonseok.ko@outlook.com>