test: Add missing header file.
The vfork & exec test program had a warning:

  tests/s-vforkexec.c: In function ‘main’:
  tests/s-vforkexec.c:31:2: warning: implicit declaration of function ‘wait’
                            [-Wimplicit-function-declaration]
    wait(NULL);
    ^

Signed-off-by: Namhyung Kim <namhyung@gmail.com>