symbol: Fix build error on 32-bit systems
Since unsigned long is not same as uint16_t like below:

  uftrace/utils/symbol.c:1144:5: error: conflicting types for
                                 ‘load_symbol_file’
   int load_symbol_file(struct symtabs *symtabs, const char *symfile,
       ^
  In file included from uftrace/uftrace.h:12:0,
                   from uftrace/utils/symbol.c:23:
  uftrace/utils/symbol.h:140:5: note: previous declaration of
                                ‘load_symbol_file’ was here
   int load_symbol_file(struct symtabs *symtabs, const char *symfile,
       ^

Signed-off-by: Namhyung Kim <namhyung@gmail.com>