pre-commit: Fix RuntimeError in isort hook
The pre-commit shows an error in isort hook as follows.

  RuntimeError: The Poetry configuration is invalid

This can be fixed by upgrading isort rev to 5.11.5 so this patch changes
the version to fix it.

In addition, apply changes from isort 5.11.5 to make pre-commit happy.

Link: https://github.com/PyCQA/isort/issues/2083#issuecomment-1408300628
Signed-off-by: Honggyu Kim <honggyu.kp@gmail.com>