Redo logging functions
Print more info like file, line number and function name.
The output now looks like below:

  ftrace: ERROR: symbol.c:163:__load_symtab: cannot find symbol information in '/usr/bin/ls'.
  Is it stripped?

The PR_FMT macro can be used to subsystem prefix ("ftrace" by default),
and it should be defined before #including "utils.h" header.

The pr_err() will add an error message (based on strerror) at the end
of the message so the message should not include terminating new line
(\n) character.

The pr_cont() skips new info and just prints the message so that it
can be used if some message are bullt by subsequent calls.

Signed-off-by: Namhyung Kim <namhyung@gmail.com>