scripts: Make lambda expression compatible for python3
Parenthesis for argument in lambda causes syntax error in python3 like below.
It's because ability to unpack tuple parameters was removed in python 3.

  ubuntu@ubuntu:~/minchul/uftrace/scripts$ python2 report-libcall.py
  ubuntu@ubuntu:~/minchul/uftrace/scripts$ python3 report-libcall.py
    File "report-libcall.py", line 26
      sorted_dict = sorted(libcall_map.iteritems(), key=lambda (k, v): (v, k), reverse=True)
                                                             ^
  SyntaxError: invalid syntax

So this commit removed parenthesis, .iteritems(), and has_key()
for python3 compatibility.

reference: https://www.python.org/dev/peps/pep-3113/

Signed-off-by: Kang Minchul <tegongkang@gmail.com>